### ISSUE TITLE
Form label elements in mobile version are not in a consistent order

### ISSUE THREAD

**Issue by RihardsJ** [fac20/Week3-ToDoList-DFJL#41]
![Screen Shot 2020-07-31 at 10 17 45](https://user-images.githubusercontent.com/48697281/89022843-8d36a300-d31a-11ea-9da4-5c9132022ac8.png)

**Comment by JoshDAO** [comment]
Thanks Rihards, this was one of the last things on our list to fix but we ran out of time!
